### ISSUE TITLE
How to restore original route and trip id?

### ISSUE THREAD

**Issue by ekleiman22** [transnetlab/transit-routing#8]
Hello,
In your algorithm you change **route_id** and **trip_id** in files stop_times.txt and trips.txt to new values. At the end of raptor function you return **new routed id**. How can I restore and receive the original one?

**Comment by Prateek1009** [comment]
Dear Ekleiman,

Thanks for pointing out the missing functionality. I have edited the GTFS wrapper to save the mappings file in the Data>GTFS>Network_name folder. Kindly note that it's been quite a while since I last worked on this project and it will take me some time for me to verify if the mappings are being generated correctly since writing a generic GTFS  wrapper is tricky. However, to avoid delay, I have pushed the changes to the development branch.  Please let me know if you detect any inconsistencies in the mapping.

**Comment by ekleiman22** [comment]
Dear Doctor Prateek Agarwal,
Thank you for the quick answer. I'll check the changes as soon as possible
and let you know.
Evgeny Kleiman

**Comment by ekleiman22** [comment]
Dear Doctor Prateek Agarwal,
Thank you for your answers and your time. I did not have any problems with your program at present.
